#Requires Autohotkey v2.0+

;; /MESSAGE TYPE/
MSG_INFO         := 1
MSG_WARN         := MSG_INFO << 1
MSG_PASS         := MSG_INFO << 2
MSG_FAIL         := MSG_INFO << 3
MSG_ERROR        := MSG_INFO << 4
MSG_DEBUG        := MSG_INFO << 5

;; /OPTIONS/
DEBUG_WINDOW     := MSG_INFO << 6
DEBUG_SCREENSHOT := MSG_INFO << 7

;; /LOGGER MODE/
DEBUG_OFF        := false
DEBUG_INFO       := MSG_INFO
DEBUG_WARNINGS   := DEBUG_INFO | MSG_WARN
DEBUG_RESULTS    := DEBUG_WARNINGS | MSG_PASS | MSG_FAIL
DEBUG_ERRORS     := DEBUG_RESULTS | MSG_ERROR
DEBUG_ALL        := DEBUG_ERRORS | DEBUG_RESULTS | DEBUG_WARNINGS | DEBUG_INFO | MSG_DEBUG
